### PR TITLE
Modify search url

### PR DESCRIPTION
**Pull request by queltosh**
Since last week search URL has changed. This is the new one that works.

### CODE REVIEW

**Comment by dawoudt** [comment]
@draogn can we verify this endpoint? Afk for a while so need extra validation before merge. Will probably have to update tests as well.

**Comment by queltosh** [comment]
Verify how? I got it by making a manual search on the website and watching the network traffic to the servers. And after appliying begins to work again.

**Comment by draogn** [comment]
Looks good to me - the updated address definitely works.  Looking at the rest of the code every other call was hitting apis.justwatch.com/content - only search_for_item was going to api.justwatch.com.   Maybe that had been deprecated and has now finally been turned off.

Don't see any changes required to the tests.

May not completely fix #32 as there's reference to total pages no longer being available.

**Comment by dawoudt** [comment]
Will try and do a release for master soon.

**Comment by drexeljoe** [comment]
How soon should we be able to install via pip? I'm still seeing v0.5.0 as the latest.

`$ pip3 install JustWatch --upgrade`
`Requirement already up-to-date: JustWatch in /usr/local/lib/python3.7/site-packages (0.5.0)`

**Comment by dawoudt** [comment]
I will try to push to pip this weekend April 25th aest. Apologies for the delay

**Pull request merged**
